### ISSUE TITLE
Make Collection view layout for New DApps

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/dapps-browser#10]
Look at https://rarebits.io/

**Comment by NickWatsonMan** [comment]
![image](https://user-images.githubusercontent.com/10436241/39971222-597e3a66-5700-11e8-90ce-eae30e87e333.png)

I have examined rarebits.io. So here is one issue. The number of symbols in descriptions vary widely. So some of cards look like this:

![image](https://user-images.githubusercontent.com/10436241/39971288-2ee2b452-5701-11e8-83f6-d7779234a3d5.png)

In order to keep all the description inside the card I had to increase the height of the box, so it's a bit higher (197x272) than on rarebits (204x262).

Also, I'm still working on the card borders design.

**Comment by vikmeup** [comment]
@NickWatsonMan images should be rounded I think, all our logos has been stored that way.

I would make it simpler and do description only in two lines or so? 

Make shadow smaller

**Comment by lovincyrus** [comment]
How's the new layout going, @NickWatsonMan ? I can take a look if you push your code to a branch.

**Comment by lovincyrus** [comment]
Fixed collection view layout: https://github.com/TrustWallet/dapps-browser/commit/fb8762c88b2dbe3b510bfb9661aebfac11fd68c3

![cards](https://user-images.githubusercontent.com/1021101/40684050-20884d0e-6345-11e8-9fec-a0dcf731536e.png)

**Comment by vikmeup** [comment]
@lovincyrus how does it look on mobile?

**Comment by lovincyrus** [comment]
Tested on multiple devices, can be seen here: 

https://www.useloom.com/share/3173612cc9324deda40b680fa76d1a29

**Comment by NickWatsonMan** [comment]
@lovincyrus @vikmeup looks good. But maybe add some space to the bottom? Between the last text line and the end of the card? What do u think?

**Comment by lovincyrus** [comment]
Good idea, fixed - https://github.com/TrustWallet/dapps-browser/commit/076538b5cf7e4717c8c34644ef207c4e279e21ac

Added more space and with even spacing between title and description.

<img width="769" alt="card" src="https://user-images.githubusercontent.com/1021101/40687127-6e7fef7c-634e-11e8-8a44-dfe2e7a2514d.png">

**Comment by vikmeup** [comment]
@lovincyrus can you show full screen?

**Comment by vikmeup** [comment]
@lovincyrus this looks good! we need to have higher quality picture for those tho! 

can you create PR?

**Comment by lovincyrus** [comment]
Definitely, @vikmeup 

I can always change the card size based on the quality of the logos.
